spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  datasource:
    url : jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  h2:
    console:
      enabled: true

  sql:
    init:
      data-locations: classpath:h2/data.sql
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


